version: "3"

services:
  wg-easy:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wg-easy
    environment:
      - WG_HOST=www.brothersbrothers.net
      - PASSWORD=${UIPassword}
      - WG_DEFAULT_DNS=192.168.0.134  # Your host IP running DNS
    hostname: wireguard-easy
    image: docker.io/weejewel/wg-easy:latest
    restart: unless-stopped
    ports:
      - "51820:51820/udp"  # WireGuard VPN port
      - "51821:51821/tcp"  # Web UI port
    volumes:
      - wg-easy_data:/etc/wireguard
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  wg-easy_data:
    driver_opts:
      type: nfs
      device: ":/Docker/wg-easy/data"
      o: nfsvers=4,addr=192.168.0.134,nolock,soft,rw
